/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.allshare.chms_1;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import mdlaf.MaterialLookAndFeel;

/**
 *
 * @author coolb
 */
public class Staff_dash extends javax.swing.JFrame {

    CardLayout cardLayout;
    private final DefaultListModel mod;

    /**
     * Creates new form Staff_dash
     */
    public Staff_dash() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        cardLayout = (CardLayout) (pnlCards.getLayout());
        menu.add(panel);
        mod = new DefaultListModel();
        list.setModel(mod);
        System.out.println("--  " + this.getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aadharBtnGroup = new javax.swing.ButtonGroup();
        menu = new javax.swing.JPopupMenu();
        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        insuranceBtnGroup = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        try{
            jPanel2 = new RoundedPanel(20,new Color(243,242,253));//javax.swing.JPanel();
            jSplitPane1 = new javax.swing.JSplitPane();
            try{
                sidebar = new RoundedPanel(20,new Color(83,71,233));//javax.swing.JPanel();
                logoutBtn = new javax.swing.JButton();
                regBtn = new javax.swing.JButton();
                profileBtn = new javax.swing.JButton();
                homeBtn = new javax.swing.JButton();
                viewBtn = new javax.swing.JButton();
                pnlCards = new javax.swing.JPanel();
                homeCard = new javax.swing.JPanel();
                srchField = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                profileCard = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                emp_user_id = new javax.swing.JLabel();
                emp_aadhar = new javax.swing.JLabel();
                emp_name = new javax.swing.JLabel();
                emp_dob = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                emp_doj = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                emp_city = new javax.swing.JLabel();
                jLabel15 = new javax.swing.JLabel();
                emp_state = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                emp_address = new javax.swing.JTextArea();
                jLabel19 = new javax.swing.JLabel();
                emp_mobile = new javax.swing.JLabel();
                jLabel20 = new javax.swing.JLabel();
                jLabel38 = new javax.swing.JLabel();
                designation = new javax.swing.JLabel();
                registerCard = new javax.swing.JScrollPane();
                regCardPnl = new javax.swing.JPanel();
                jLabel21 = new javax.swing.JLabel();
                yesRadio1 = new javax.swing.JRadioButton();
                noRadio1 = new javax.swing.JRadioButton();
                jLabel22 = new javax.swing.JLabel();
                jLabel23 = new javax.swing.JLabel();
                jLabel24 = new javax.swing.JLabel();
                jLabel25 = new javax.swing.JLabel();
                jLabel26 = new javax.swing.JLabel();
                jLabel27 = new javax.swing.JLabel();
                jLabel28 = new javax.swing.JLabel();
                jLabel29 = new javax.swing.JLabel();
                jLabel30 = new javax.swing.JLabel();
                jLabel31 = new javax.swing.JLabel();
                jLabel32 = new javax.swing.JLabel();
                jLabel33 = new javax.swing.JLabel();
                jLabel34 = new javax.swing.JLabel();
                jLabel35 = new javax.swing.JLabel();
                aadharNo1 = new javax.swing.JTextField();
                name1 = new javax.swing.JTextField();
                gender1 = new javax.swing.JTextField();
                dob1 = new javax.swing.JTextField();
                address1 = new javax.swing.JTextField();
                emailId1 = new javax.swing.JTextField();
                mobile1 = new javax.swing.JTextField();
                occupation1 = new javax.swing.JTextField();
                guardian1 = new javax.swing.JTextField();
                relationship1 = new javax.swing.JTextField();
                ref_doc1 = new javax.swing.JTextField();
                jButton4 = new javax.swing.JButton();
                jLabel36 = new javax.swing.JLabel();
                jLabel37 = new javax.swing.JLabel();
                city1 = new javax.swing.JTextField();
                jRadioButton1 = new javax.swing.JRadioButton();
                jRadioButton2 = new javax.swing.JRadioButton();
                insurer1 = new javax.swing.JComboBox<>();
                state1 = new javax.swing.JComboBox<>();
                viewPatPnl = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jLabel39 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jComboBox3 = new javax.swing.JComboBox<>();
                jLabel40 = new javax.swing.JLabel();
                jCheckBox1 = new javax.swing.JCheckBox();
                jCheckBox2 = new javax.swing.JCheckBox();
                jCheckBox3 = new javax.swing.JCheckBox();
                jCheckBox4 = new javax.swing.JCheckBox();
                jCheckBox5 = new javax.swing.JCheckBox();
                jCheckBox6 = new javax.swing.JCheckBox();
                jCheckBox7 = new javax.swing.JCheckBox();
                jCheckBox8 = new javax.swing.JCheckBox();
                jCheckBox9 = new javax.swing.JCheckBox();
                jCheckBox10 = new javax.swing.JCheckBox();
                jCheckBox11 = new javax.swing.JCheckBox();
                jCheckBox12 = new javax.swing.JCheckBox();
                jCheckBox13 = new javax.swing.JCheckBox();
                jButton3 = new javax.swing.JButton();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();

                menu.setFocusable(false);

                list.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                list.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
                jScrollPane1.setViewportView(list);

                javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
                panel.setLayout(panelLayout);
                panelLayout.setHorizontalGroup(
                    panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                panelLayout.setVerticalGroup(
                    panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jToolBar1.setRollover(true);

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
            jPanel2.setOpaque(false);

            //{
                //    private final int location = 200;
                //    {
                    //
                    //        setDividerLocation( jel1.getWidth() );
                    //    }Pan
                //    @Override
                //    public int getDividerLocation() {
                    //        return sidebar.getWidth() ;
                    //    }
                //    @Override
                //    public int getLastDividerLocation() {
                    //        return sidebar.getWidth() ;
                    //    }
                //}
            jSplitPane1.setEnabled(false);
            jSplitPane1.setOpaque(false);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        sidebar.setOpaque(false);

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logoutBtn.setText(" ");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        regBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/register.png"))); // NOI18N
        regBtn.setText(" ");
        regBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regBtnMouseExited(evt);
            }
        });
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        profileBtn.setText(" ");
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnMouseExited(evt);
            }
        });
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        homeBtn.setText(" ");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        viewBtn.setText(" ");
        viewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewBtnMouseExited(evt);
            }
        });
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(profileBtn)
                .addGap(55, 55, 55)
                .addComponent(viewBtn)
                .addGap(53, 53, 53)
                .addComponent(regBtn)
                .addGap(283, 283, 283)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(sidebar);

        pnlCards.setLayout(new java.awt.CardLayout());

        homeCard.setBackground(new java.awt.Color(243, 242, 253));

        srchField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        srchField.setText("Search your symptoms....");
        srchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                srchFieldFocusLost(evt);
            }
        });
        srchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                srchFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srchFieldKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doc.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Do you have Symptoms of COVID-19?");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Contact a Doctor");

        javax.swing.GroupLayout homeCardLayout = new javax.swing.GroupLayout(homeCard);
        homeCard.setLayout(homeCardLayout);
        homeCardLayout.setHorizontalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCardLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(srchField)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(homeCardLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        homeCardLayout.setVerticalGroup(
            homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeCardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(srchField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homeCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pnlCards.add(homeCard, "homeCard");

        profileCard.setBackground(new java.awt.Color(243, 242, 253));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Date of Birth");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("User ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Aadhar Number");

        emp_user_id.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_user_id.setText("To Be Displayed");

        emp_aadhar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_aadhar.setText("To Be Displayed");

        emp_name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_name.setText("To Be Displayed");

        emp_dob.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_dob.setText("To Be Displayed");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Date of Joining");

        emp_doj.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_doj.setText("To Be Displayed");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("City");

        emp_city.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_city.setText("To Be Displayed");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("State");

        emp_state.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_state.setText("To Be Displayed");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Address");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        emp_address.setColumns(20);
        emp_address.setRows(5);
        jScrollPane2.setViewportView(emp_address);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText("Mobile");

        emp_mobile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emp_mobile.setText("To Be Displayed");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("View Profile");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 255)));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel38.setText("Designation");

        designation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        designation.setText("To Be Displayed");

        javax.swing.GroupLayout profileCardLayout = new javax.swing.GroupLayout(profileCard);
        profileCard.setLayout(profileCardLayout);
        profileCardLayout.setHorizontalGroup(
            profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emp_city, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emp_user_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emp_aadhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emp_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emp_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emp_doj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emp_state, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emp_mobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(profileCardLayout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(designation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        profileCardLayout.setVerticalGroup(
            profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emp_user_id))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emp_aadhar))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emp_name))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emp_dob))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(emp_doj))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emp_city))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(emp_state))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(emp_mobile))
                .addGap(18, 18, 18)
                .addGroup(profileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(designation))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pnlCards.add(profileCard, "profileCard");

        registerCard.setBackground(new java.awt.Color(243, 242, 253));

        regCardPnl.setBackground(new java.awt.Color(243, 242, 253));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setText("Register with Aadhar Card?");

        yesRadio1.setBackground(new java.awt.Color(243, 242, 253));
        aadharBtnGroup.add(yesRadio1);
        yesRadio1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        yesRadio1.setText("Yes");
        yesRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesRadio1ActionPerformed(evt);
            }
        });

        noRadio1.setBackground(new java.awt.Color(243, 242, 253));
        aadharBtnGroup.add(noRadio1);
        noRadio1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        noRadio1.setText("No");
        noRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRadio1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setText("Aadhar Number:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setText("Name:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setText("Gender:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel25.setText("Date of Birth (DDMMYYYY):");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel26.setText("Address:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setText("Email - ID:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel28.setText("Mobile No:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel29.setText("Occupation:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel30.setText("Guardian:");

        jLabel31.setText("(In case of minor patient)");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel32.setText("Relationship:");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel33.setText("Insurance:");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel34.setText("Insurer:");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel35.setText("Referring Doctor");

        aadharNo1.setEditable(false);
        aadharNo1.setBackground(new java.awt.Color(255, 255, 255));
        aadharNo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        name1.setEditable(false);
        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        gender1.setEditable(false);
        gender1.setBackground(new java.awt.Color(255, 255, 255));
        gender1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        dob1.setEditable(false);
        dob1.setBackground(new java.awt.Color(255, 255, 255));
        dob1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        address1.setBackground(new java.awt.Color(255, 255, 255));
        address1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        emailId1.setBackground(new java.awt.Color(255, 255, 255));
        emailId1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mobile1.setBackground(new java.awt.Color(255, 255, 255));
        mobile1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        occupation1.setEditable(false);
        occupation1.setBackground(new java.awt.Color(255, 255, 255));
        occupation1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        guardian1.setBackground(new java.awt.Color(255, 255, 255));
        guardian1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        relationship1.setBackground(new java.awt.Color(255, 255, 255));
        relationship1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        ref_doc1.setBackground(new java.awt.Color(255, 255, 255));
        ref_doc1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel36.setText("State");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel37.setText("City");

        city1.setBackground(new java.awt.Color(255, 255, 255));
        city1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jRadioButton1.setBackground(new java.awt.Color(243, 242, 253));
        insuranceBtnGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(243, 242, 253));
        insuranceBtnGroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        insurer1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        insurer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        state1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        state1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout regCardPnlLayout = new javax.swing.GroupLayout(regCardPnl);
        regCardPnl.setLayout(regCardPnlLayout);
        regCardPnlLayout.setHorizontalGroup(
            regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regCardPnlLayout.createSequentialGroup()
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regCardPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(regCardPnlLayout.createSequentialGroup()
                                    .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(regCardPnlLayout.createSequentialGroup()
                                            .addGap(72, 72, 72)
                                            .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(regCardPnlLayout.createSequentialGroup()
                                                    .addComponent(yesRadio1)
                                                    .addGap(58, 58, 58)
                                                    .addComponent(noRadio1))
                                                .addComponent(aadharNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regCardPnlLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(regCardPnlLayout.createSequentialGroup()
                                                    .addComponent(jRadioButton1)
                                                    .addGap(58, 58, 58)
                                                    .addComponent(jRadioButton2))
                                                .addComponent(gender1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(dob1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(address1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(emailId1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(mobile1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(occupation1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(guardian1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(relationship1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(ref_doc1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(city1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                                .addComponent(insurer1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(state1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addComponent(jLabel21)))
                    .addGroup(regCardPnlLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        regCardPnlLayout.setVerticalGroup(
            regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regCardPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(yesRadio1)
                    .addComponent(noRadio1))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(aadharNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(dob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(state1))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(city1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(emailId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(mobile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(occupation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(guardian1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(relationship1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(insurer1))
                .addGap(18, 18, 18)
                .addGroup(regCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(ref_doc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton4)
                .addGap(20, 20, 20))
        );

        registerCard.setViewportView(regCardPnl);

        pnlCards.add(registerCard, "registerCard");

        viewPatPnl.setBackground(new java.awt.Color(243, 242, 253));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("View / Search Patient Details");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel39.setText("Search");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setText("Keyword");

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient ID", "Aadhar Number", "Name", "Gender", "Date of Birth", "State", "City", "Address", "Email-ID", "Mobile Number", "Occupation", "Guardian", "Insurer", "Referring Doctor" }));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel40.setText("Details You Want to See");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("Aadhar Number");

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Gender");

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox3.setText("Date of Birth");

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox4.setText("State");

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox5.setText("Mobile Number");

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox6.setText("City");

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox7.setText("Address");

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox8.setText("Referring Doctor");

        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox9.setText("Email ID");

        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox10.setText("Occupation");

        jCheckBox11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox11.setText("Guardian");

        jCheckBox12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox12.setText("Insurer");

        jCheckBox13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox13.setText("All");

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Info"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout viewPatPnlLayout = new javax.swing.GroupLayout(viewPatPnl);
        viewPatPnl.setLayout(viewPatPnlLayout);
        viewPatPnlLayout.setHorizontalGroup(
            viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPatPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(viewPatPnlLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewPatPnlLayout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewPatPnlLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox2)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox3)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox4))
                            .addGroup(viewPatPnlLayout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox6)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox7)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox8))
                            .addGroup(viewPatPnlLayout.createSequentialGroup()
                                .addComponent(jCheckBox9)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox10)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox11)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox12)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox13))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        viewPatPnlLayout.setVerticalGroup(
            viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPatPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewPatPnlLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPatPnlLayout.createSequentialGroup()
                        .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4))
                        .addGap(18, 18, 18)
                        .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8))
                        .addGap(18, 18, 18)
                        .addGroup(viewPatPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox11)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox13)))
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlCards.add(viewPatPnl, "viewPatCard");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        System.out.println(jSplitPane1.getDividerLocation());
        logoutBtn.setText("Logout");
        logoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\logout (1).png"));
        jSplitPane1.setDividerLocation(200);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() + 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() + 130, jSplitPane1.getHeight());
        menu.setVisible(false);
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        System.out.println(jSplitPane1.getDividerLocation());
        logoutBtn.setText(" ");
        logoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\logout.png"));
        jSplitPane1.setDividerLocation(90);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() - 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() - 130, jSplitPane1.getHeight());
    }//GEN-LAST:event_logoutBtnMouseExited

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void regBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBtnMouseEntered
        regBtn.setText("Register New Patient");
        regBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\register (1).png"));
        jSplitPane1.setDividerLocation(200);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() + 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() + 130, jSplitPane1.getHeight());
        menu.setVisible(false);
    }//GEN-LAST:event_regBtnMouseEntered

    private void regBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBtnMouseExited
        regBtn.setText(" ");
        regBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\register.png"));
        jSplitPane1.setDividerLocation(90);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() - 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() - 130, jSplitPane1.getHeight());
    }//GEN-LAST:event_regBtnMouseExited

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        cardLayout.show(pnlCards, "registerCard");
    }//GEN-LAST:event_regBtnActionPerformed

    private void profileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseEntered
        profileBtn.setText("Profile");
        profileBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\user (1).png"));
        jSplitPane1.setDividerLocation(200);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() + 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() + 130, jSplitPane1.getHeight());
        menu.setVisible(false);
    }//GEN-LAST:event_profileBtnMouseEntered

    private void profileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseExited
        profileBtn.setText(" ");
        profileBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\user.png"));
        jSplitPane1.setDividerLocation(90);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() - 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() - 130, jSplitPane1.getHeight());
    }//GEN-LAST:event_profileBtnMouseExited

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        cardLayout.show(pnlCards, "profileCard");
    }//GEN-LAST:event_profileBtnActionPerformed

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        homeBtn.setText("Home");
        homeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\home (1).png"));
        jSplitPane1.setDividerLocation(200);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() + 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() + 130, jSplitPane1.getHeight());
        menu.setVisible(false);
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        homeBtn.setText(" ");
        homeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\home.png"));
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() - 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() - 130, jSplitPane1.getHeight());
        jSplitPane1.setDividerLocation(90);
    }//GEN-LAST:event_homeBtnMouseExited

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        cardLayout.show(pnlCards, "homeCard");
    }//GEN-LAST:event_homeBtnActionPerformed

    private void srchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srchFieldFocusLost

    }//GEN-LAST:event_srchFieldFocusLost
    boolean flag = false;
    private void srchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyPressed

        if (!flag) {
            srchField.setText("");
            flag = true;
        }
        String search = srchField.getText().trim();
        String[] strArray = {"Fever", "Dry cough", "Tiredness", "Aches and pains", "Sore throat", "Diarrhoea", "Conjunctivitis", "Headache", "Loss of taste or smell", "A rash on skin, or discolouration of fingers or toes", "Difficulty breathing or shortness of breath", "Chest pain or pressure", "Loss of speech or movement"};
        if (!search.equals("")) {
            mod.removeAllElements();
            for (int i = 0; i < strArray.length; i++) {
                
                if (strArray[i].contains(search)) {
                    mod.addElement(strArray[i]);
                }
            }
            menu.show(srchField, 0, srchField.getHeight());
        }
    }//GEN-LAST:event_srchFieldKeyPressed

    private void srchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchFieldKeyReleased

    }//GEN-LAST:event_srchFieldKeyReleased
    long aadhar_number = 0;
    String name;
    String gender;
    String dob;
    String state;
    String city;
    String address;
    String email;
    long mobile_no;
    String occupation;
    String guardian;
    String relationship;
    int insurance;
    String insurer;
    String ref_doc;

    boolean radioCheck = false;
    private void yesRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesRadio1ActionPerformed
        radioCheck = true;
        String aadhar = JOptionPane.showInputDialog(this, "Enter Aadhar number ");
        Connection mycon = null;
        Statement stmnt = null;
        ResultSet myrs = null;
        try {
            mycon = DriverManager.getConnection("jdbc:mysql://localhost:3306/chms", "root", "Asif@123");
            stmnt = mycon.createStatement();
            aadhar_number = Long.parseLong(aadhar);
            String query = "Select * from aadhar_db where aadhar_no = " + aadhar_number;
            myrs = stmnt.executeQuery(query);
            while (myrs.next()) {
                name = myrs.getString("name");
                gender = myrs.getString("gender");
                dob = myrs.getString("dob");
                state = myrs.getString("state");
                city = myrs.getString("city");
                address = myrs.getString("address");
                email = myrs.getString("email_id");
                mobile_no = myrs.getLong("mobile_no");

                aadharNo1.setText(aadhar);
                name1.setText(name);
                gender1.setText(gender);
                dob1.setText(dob);
                state1.addItem(state);
                city1.setText(city);
                address1.setText(address);
                emailId1.setText(email);
                mobile1.setText(String.valueOf(mobile_no));

            }
        } catch (Exception exc) {
            exc.printStackTrace();
        } finally {
            if (myrs != null) {
                try {
                    myrs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Staff_login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (stmnt != null) {
                try {
                    stmnt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Staff_login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        state1.setEditable(false);
        city1.setEditable(false);
        address1.setEditable(false);
        gender1.setEditable(false);
        name1.setEditable(false);
        aadharNo1.setEditable(false);
        dob1.setEditable(false);
        emailId1.setEditable(false);
        mobile1.setEditable(false);
        state1.setEnabled(false);

    }//GEN-LAST:event_yesRadio1ActionPerformed

    private void noRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRadio1ActionPerformed
        city1.setEditable(true);
        address1.setEditable(true);
        gender1.setEditable(true);
        name1.setEditable(true);
        aadharNo1.setEditable(true);
        dob1.setEditable(true);
        emailId1.setEditable(true);
        mobile1.setEditable(true);
        state1.setEnabled(true);

        state1.addItem("Andaman and Nicobar Islands");
        state1.addItem("Andhra Pradesh");
        state1.addItem("Arunachal Pradesh");
        state1.addItem("Assam");
        state1.addItem("Bihar");
        state1.addItem("Chandigarh");
        state1.addItem("Chhattisgarh");
        state1.addItem("Dadra and Nagar Haveli");
        state1.addItem("Daman and Diu");
        state1.addItem("Delhi");
        state1.addItem("Goa");
        state1.addItem("Gujarat");
        state1.addItem("Haryana");
        state1.addItem("Himachal Pradesh");
        state1.addItem("Jammu and Kashmir");
        state1.addItem("Jharkhand");
        state1.addItem("Karnataka");
        state1.addItem("Kerala");
        state1.addItem("Lakshadweep");
        state1.addItem("Madhya Pradesh");
        state1.addItem("Maharashtrah");
        state1.addItem("Manipur");
        state1.addItem("Meghalaya");
        state1.addItem("Mizoram");
        state1.addItem("Nagaland");
        state1.addItem("Odisha");
        state1.addItem("Punjab");
        state1.addItem("Rajasthan");
        state1.addItem("Tamil Nadu");
        state1.addItem("Telangana");
        state1.addItem("Tripura");
        state1.addItem("Uttar Pradesh");
        state1.addItem("Uttarakhand");
        state1.addItem("West Bengal");
    }//GEN-LAST:event_noRadio1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        insurance = 0;
        insurer1.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        cardLayout.show(pnlCards, "viewPatCard");
    }//GEN-LAST:event_viewBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void viewBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseEntered
        viewBtn.setText("View/Search Patient Details");
        viewBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\search (1).png"));
        jSplitPane1.setDividerLocation(200);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() + 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() + 130, jSplitPane1.getHeight());
        menu.setVisible(false);
    }//GEN-LAST:event_viewBtnMouseEntered

    private void viewBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseExited
        viewBtn.setText(" ");
        viewBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\coolb\\Downloads\\NetBeansProjects\\CHMS_1\\src\\main\\resources\\search.png"));
        jSplitPane1.setDividerLocation(90);
        jPanel2.setBounds(jPanel2.getX(), jPanel2.getY(), jPanel2.getWidth() - 130, jPanel2.getHeight());
        jSplitPane1.setBounds(jSplitPane1.getX(), jSplitPane1.getY(), jSplitPane1.getWidth() - 130, jSplitPane1.getHeight());
    }//GEN-LAST:event_viewBtnMouseExited

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        insurance = 1;
        insurer1.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        name = name1.getText();
        gender = gender1.getText();
        dob = dob1.getText();
        state = state1.getSelectedItem().toString();
        if (!aadharNo1.getText().isEmpty()) {
            aadhar_number = Long.parseLong(aadharNo1.getText());
        }
        city = city1.getText();
        address = address1.getText();
        email = emailId1.getText();
        if (!mobile1.getText().isEmpty()) {
            mobile_no = Long.parseLong(mobile1.getText());
        }
        occupation = occupation1.getText();
        guardian = guardian1.getText();
        relationship = relationship1.getText();
        insurer = insurer1.getSelectedItem().toString();
        ref_doc = ref_doc1.getText();

        Connection mycon = null;
        Statement stmnt = null;
        ResultSet myrs = null;
        try {
            mycon = DriverManager.getConnection("jdbc:mysql://localhost:3306/chms", "root", "Asif@123");
            stmnt = mycon.createStatement();
            String query = "Select * from patient_details";
//            boolean aadhar_number_exists = false;
            myrs = stmnt.executeQuery(query);
            int patient_id = 100000;
            while (myrs.next()) {
                patient_id++;
            }
            query = String.format("INSERT INTO `chms`.`patient_personal_details` (`pateint_id`, `aadhar_number`, `name`, `gender`, `dob`, `address`, `email_id`, `mobile_no`, `state`, `city`) VALUES ('%d', '%d', '%s', '%s', '%s', '%s', '%s', '%d', '%s', '%s')", patient_id, aadhar_number, name, gender, dob, address, email, mobile_no, state, city);
            int myrs1 = stmnt.executeUpdate(query);
            query = String.format("INSERT INTO `chms`.`patient_details` (`patient_id`, `occupation`, `guardian`, `relationship`, `insurance`, `insurer`, `referring_doctor`) VALUES ('%d', '%s', '%s', '%s', '%d', '%s', '%s')", patient_id, occupation, guardian, relationship, insurance, insurer, ref_doc);
            int myrs2 = stmnt.executeUpdate(query);
            if (myrs1 == 0) {
                JOptionPane.showMessageDialog(this, "Fill all the details", "Dialog", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Details successfully saved", "Dialog", JOptionPane.OK_OPTION);
                cardLayout.show(pnlCards, "homeCard");
            }
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this, "Fill all the details", "Dialog", JOptionPane.ERROR_MESSAGE);
            exc.printStackTrace();
        } finally {
            if (myrs != null) {
                try {
                    myrs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Staff_login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (stmnt != null) {
                try {
                    stmnt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(Staff_login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        MaterialLookAndFeel lf = new MaterialLookAndFeel();
        UIManager.setLookAndFeel(lf);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aadharBtnGroup;
    private javax.swing.JTextField aadharNo1;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField city1;
    public javax.swing.JLabel designation;
    private javax.swing.JTextField dob1;
    private javax.swing.JTextField emailId1;
    public javax.swing.JLabel emp_aadhar;
    public javax.swing.JTextArea emp_address;
    public javax.swing.JLabel emp_city;
    public javax.swing.JLabel emp_dob;
    public javax.swing.JLabel emp_doj;
    public javax.swing.JLabel emp_mobile;
    public javax.swing.JLabel emp_name;
    public javax.swing.JLabel emp_state;
    public javax.swing.JLabel emp_user_id;
    private javax.swing.JTextField gender1;
    private javax.swing.JTextField guardian1;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel homeCard;
    private javax.swing.ButtonGroup insuranceBtnGroup;
    private javax.swing.JComboBox<String> insurer1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JTextField mobile1;
    private javax.swing.JTextField name1;
    private javax.swing.JRadioButton noRadio1;
    private javax.swing.JTextField occupation1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JButton profileBtn;
    private javax.swing.JPanel profileCard;
    private javax.swing.JTextField ref_doc1;
    private javax.swing.JButton regBtn;
    private javax.swing.JPanel regCardPnl;
    private javax.swing.JScrollPane registerCard;
    private javax.swing.JTextField relationship1;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextField srchField;
    private javax.swing.JComboBox<String> state1;
    private javax.swing.JButton viewBtn;
    private javax.swing.JPanel viewPatPnl;
    private javax.swing.JRadioButton yesRadio1;
    // End of variables declaration//GEN-END:variables
}
